# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97f70b6230a5f961e8362809f1d3ec7fb39662741e98b222ecb43de0d6f2853c50243b8424620e7161773a872d23606ed781b19de84562cd2836c35ba4460e0d

test:
  secret_key_base: e82bc7155f009c5aa3253834d55490197615518bbfbfed8d4640a5b10546981c6825eff32abca47cc1755b2d1bcde3bdfe7ffcb4e8827197dad2584c64e877aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
